# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 8168cc77-capi-aws
  namespace: 8168cc77
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 8168cc77-capi-aws
subjects:
- kind: ServiceAccount
  name: 8168cc77-capi-aws
